plugin: amazon.aws.aws_ec2

regions:
  - eu-central-1

filters:
  tag:Name: innovatech-cs1-web
  instance-state-name: running

hostnames:
  - instance-id

groups:
  webservers: true

compose:
  ansible_connection: '"amazon.aws.aws_ssm"'
  ansible_aws_ssm_region: '"eu-central-1"'
  ansible_aws_ssm_bucket_name: '"innovatech-cs1-ansible-ssm-daa20da28fd66da25f2fe46f40"'