name: Application Deployment

on:
  push:
    branches:
      - main
    paths:
      - "ansible/**"
      - "app/**"
      - ".github/workflows/application.yml"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy application
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Ansible installation
        run: ansible --version

      - name: Get Ansible SSM bucket from Terraform
        id: terraform-output
        working-directory: terraform
        run: |
          echo "bucket_name=$(terraform output -raw ansible_ssm_bucket_name)" >> "$GITHUB_OUTPUT"

      - name: Deploy application with Ansible
        run: |
          ansible-playbook \
            -i ansible/inventory/aws_ec2.yml \
            ansible/playbooks/webserver.yml \
            -e "ansible_aws_ssm_bucket_name=${{ steps.terraform-output.outputs.bucket_name }}"